"""marketplace foundation: organizations, rfps, solutions

Revision ID: c11f09a3a44d
Revises: da05f3e09e10
Create Date: 2026-07-09 21:57:23.624583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11f09a3a44d'
down_revision: Union[str, None] = 'da05f3e09e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('rfp_free_quota_used', sa.Integer(), nullable=False),
    sa.Column('rfp_free_quota_limit', sa.Integer(), nullable=False),
    sa.Column('billing_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('rfps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('timeline', sa.String(length=300), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('geography', sa.String(length=200), nullable=False),
    sa.Column('resolution_mode', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promoted_problem_id', sa.String(length=36), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfps_organization_id'), 'rfps', ['organization_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('category_tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_organization_id'), 'solutions', ['organization_id'], unique=False)
    op.create_table('rfp_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfp_id', sa.String(length=36), nullable=False),
    sa.Column('attribute_key', sa.String(length=200), nullable=False),
    sa.Column('attribute_value', sa.String(length=1000), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_hard_constraint', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_requirements_rfp_id'), 'rfp_requirements', ['rfp_id'], unique=False)
    op.create_table('solution_attributes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('solution_id', sa.String(length=36), nullable=False),
    sa.Column('attribute_key', sa.String(length=200), nullable=False),
    sa.Column('attribute_value', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_attributes_solution_id'), 'solution_attributes', ['solution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_attributes_solution_id'), table_name='solution_attributes')
    op.drop_table('solution_attributes')
    op.drop_index(op.f('ix_rfp_requirements_rfp_id'), table_name='rfp_requirements')
    op.drop_table('rfp_requirements')
    op.drop_index(op.f('ix_solutions_organization_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_rfps_organization_id'), table_name='rfps')
    op.drop_table('rfps')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_table('organizations')
    # ### end Alembic commands ###
