"""moderation override baseline

Revision ID: da05f3e09e10
Revises: 53bc84afb894
Create Date: 2026-07-09 17:49:13.139523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da05f3e09e10'
down_revision: Union[str, None] = '53bc84afb894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_override_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_override_events_target_id'), 'moderation_override_events', ['target_id'], unique=False)
    # server_default=false() (hand-added, not autogenerate output): these
    # are new NOT NULL boolean columns on tables that may already have
    # rows (comments/feed_posts/users all predate this migration). A
    # bare ADD COLUMN ... NOT NULL with no default would fail against any
    # existing row. The server_default backfills existing rows to False
    # at the DB level in the same statement; SQLAlchemy's ORM-side
    # `default=False` (see the model classes) covers new rows from here
    # on, so the server_default only matters for this one migration.
    op.add_column('comments', sa.Column('hidden', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('feed_posts', sa.Column('hidden', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    op.drop_column('feed_posts', 'hidden')
    op.drop_column('comments', 'hidden')
    op.drop_index(op.f('ix_moderation_override_events_target_id'), table_name='moderation_override_events')
    op.drop_table('moderation_override_events')
    # ### end Alembic commands ###
