"""marketplace embedding vectors

Revision ID: f02dd236afbf
Revises: c1454ec57882
Create Date: 2026-07-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

try:
    from pgvector.sqlalchemy import Vector
except ImportError:  # pragma: no cover - pgvector always installed per pyproject.toml
    Vector = None


# revision identifiers, used by Alembic.
revision: str = 'f02dd236afbf'
down_revision: Union[str, None] = 'c1454ec57882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# text-embedding-3-small's native output dimensionality — must match
# app/models/marketplace/embedding.py's EMBEDDING_DIMENSIONS constant.
EMBEDDING_DIMENSIONS = 1536


def upgrade() -> None:
    # Guarded rather than unconditional: `env.py` always points Alembic
    # at the real DATABASE_URL (see that module's docstring — normalized
    # to `postgresql+psycopg://`), so in practice this migration only
    # ever runs against Postgres. The guard exists anyway per the build
    # brief, in case this migration is ever invoked in a context pointed
    # at a non-Postgres engine (e.g. a future offline-mode / alternate
    # test harness) — `CREATE EXTENSION` and the native `vector` column
    # type below are both Postgres-only and would hard-fail elsewhere.
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    if is_postgres:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        vector_type = Vector(EMBEDDING_DIMENSIONS)
    else:  # pragma: no cover - defensive only, see comment above
        vector_type = sa.JSON()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_vectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_space', sa.String(length=100), nullable=False),
    sa.Column('vector', vector_type, nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_vectors_owner_type'), 'embedding_vectors', ['owner_type'], unique=False)
    op.create_index(op.f('ix_embedding_vectors_owner_id'), 'embedding_vectors', ['owner_id'], unique=False)
    op.create_index(op.f('ix_embedding_vectors_embedding_space'), 'embedding_vectors', ['embedding_space'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_vectors_embedding_space'), table_name='embedding_vectors')
    op.drop_index(op.f('ix_embedding_vectors_owner_id'), table_name='embedding_vectors')
    op.drop_index(op.f('ix_embedding_vectors_owner_type'), table_name='embedding_vectors')
    op.drop_table('embedding_vectors')
    # Note: intentionally NOT dropping the `vector` extension here — other
    # tables/migrations may come to depend on it, and DROP EXTENSION would
    # be destructive beyond this migration's own table.
    # ### end Alembic commands ###
