"""EmbeddingVector ORM model (GitHub issue #67).

Stores one embedding per (owner, embedding_space, model) combination,
generated by whatever provider `app/services/embeddings_provider.py`
resolves to (see that module's docstring — real provider is OpenAI
`text-embedding-3-small`, mockable for local dev/tests). See CLAUDE.md
"Solution Marketplace Architecture" -> "Domain model" (`EmbeddingVector`)
and -> "Embeddings provider".

**Insert-only**, same immutability rule as `CommitmentCheckpoint`
(`app/models/checkpoint.py`) and `ModerationOverrideEvent`
(`app/models/moderation.py`): a content edit (an RFP or Solution's
description changes) generates a NEW `EmbeddingVector` row, old ones are
kept, never updated or deleted in place. This matters for the same
auditing reason as elsewhere in this codebase, plus a matching-specific
one: `MatchRun`/`SolutionMatch` (later phase, #68) records which
embedding row(s) fed a given match computation, so historical match
explanations stay reproducible even after content and its embedding
change again later. Nothing in this module (or anywhere yet — no caller
exists until #68) should ever UPDATE or DELETE a row here; only
`app/services/embeddings_provider.py`'s `generate_and_store_embedding`
INSERTs new rows. Callers needing "the current embedding" for a given
owner+space should query the most recent row by `generated_at`.

`owner_type` + `owner_id` (rather than two nullable FK columns, one per
owner type) mirrors `ModerationOverrideEvent.target_type`/`target_id`'s
polymorphic-reference pattern — deliberately not an FK constraint, since
a single column pair needs to reference either `rfps.id` or
`solutions.id` depending on `owner_type`.

`embedding_space` is a plain named string column (not a DB enum) for the
same "iteration speed over DB-level strictness" reasoning as
`Problem.tier` / `RFP.resolution_mode` — CLAUDE.md's own "Open questions"
section says the concrete space vocabulary ("summary", "technical_spec",
"industry_context") is "a starting proposal, not a final schema", so this
deliberately doesn't hard-code that set at the DB level. RFP and Solution
embeddings are only ever compared *within* the same named space, never
across (enforced by callers in the later matching-engine phase, not by
this model).

`vector`'s storage tradeoff (Postgres pgvector vs. this repo's SQLite
integration-test harness) is documented on `PortableVector` below.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON, TypeDecorator

from app.core.time import utcnow
from app.db.base import Base

# text-embedding-3-small's native output dimensionality — see
# app/services/embeddings_provider.py DEFAULT_DIMENSIONS docstring for
# why this value specifically. Kept here too since the pgvector column
# type is fixed-dimension at the DB level (`VECTOR(n)`); both call sites
# must agree, so this is the one place that gets imported by the other.
EMBEDDING_DIMENSIONS = 1536


class PortableVector(TypeDecorator):
    """A vector column type that renders as native `pgvector.sqlalchemy.
    Vector` on Postgres, and falls back to a JSON-serialized list of
    floats on every other dialect.

    Why this exists: CLAUDE.md specifies Postgres + the `pgvector`
    extension for production vector storage ("Store vectors in Postgres
    via the pgvector extension rather than standing up a separate vector
    database"). But this repo's integration test suite runs against an
    in-memory SQLite database (`tests/integration/conftest.py`), created
    via `Base.metadata.create_all()` — not through Alembic migrations at
    all. `pgvector.sqlalchemy.Vector` is a `UserDefinedType` that emits
    Postgres-only DDL (`VECTOR(n)`) and has no SQLite equivalent, so
    using it directly would make every SQLite-backed test that touches
    this table fail at `create_all()` time, before a single test even
    runs.

    This is SQLAlchemy's standard `TypeDecorator` + `load_dialect_impl`
    pattern for a type that needs different underlying column behavior
    per dialect (see SQLAlchemy docs, custom types guide):
    `load_dialect_impl` is called once per bound `Engine` to pick the
    real underlying `TypeEngine` for that dialect, and
    `process_bind_param`/`process_result_value` adapt Python values <->
    that underlying representation.

    Tradeoff accepted here: on SQLite, the vector is stored as a JSON
    array with NO index and NO native distance operators (`<->`, `<=>`,
    etc.) — cosine-similarity ranking (CLAUDE.md's matching-engine
    "Rank, don't just score" step) can only run in Python against
    SQLite-backed data, never pushed down to SQL. That's fine for this
    repo's SQLite usage (unit/integration tests only — never a real
    deployment target, see CLAUDE.md "Local Development Environment":
    "not representative of the production data tier"); production
    Postgres gets the real indexed `pgvector` column and can do the
    similarity search in-database once the matching engine (#68) is
    built. If SQLite were ever used to actually exercise ranking logic
    at scale, this tradeoff would need revisiting — it is not for this
    issue's scope (no ranking logic is built here at all).
    """

    impl = JSON
    cache_ok = True

    def __init__(self, dimensions: int = EMBEDDING_DIMENSIONS, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.dimensions = dimensions

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            from pgvector.sqlalchemy import Vector

            return dialect.type_descriptor(Vector(self.dimensions))
        return dialect.type_descriptor(JSON())

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        # On Postgres, hand the raw list straight to pgvector's Vector
        # type (it does its own bind-param encoding). On every other
        # dialect (SQLite), JSON's own bind handling takes it from here.
        return list(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        return list(value)


class EmbeddingVector(Base):
    __tablename__ = "embedding_vectors"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )

    # Polymorphic reference, not an FK — mirrors
    # ModerationOverrideEvent.target_type/target_id (see module
    # docstring). Values: "rfp" | "solution".
    owner_type: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    owner_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # Named embedding space, e.g. "summary", "technical_spec",
    # "industry_context" — see module docstring on why this isn't a DB
    # enum yet.
    embedding_space: Mapped[str] = mapped_column(String(100), nullable=False, index=True)

    vector: Mapped[list[float]] = mapped_column(PortableVector(EMBEDDING_DIMENSIONS), nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False, default=EMBEDDING_DIMENSIONS)

    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), nullable=False, default="")

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow
    )
